/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prakpbo.kalkulator;

/**
 *
 * @author zhida
 */
public class KalkulatorFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(KalkulatorFrame.class.getName());

    /**
     * Creates new form KalkulatorFrame
     */

    double numEnter1;
    double numEnter2;
    double result;
    String op;
    
    public KalkulatorFrame() {
        initComponents();    
        setResizable(false);
        setTitle("Kalkulator");
        getContentPane().setBackground(new java.awt.Color(18,18,18));
        
    }

    private void enterNumbers(String number) {
        String nums = resultLabel.getText() + number;
        resultLabel.setText(nums);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        percentBtn = new javax.swing.JButton();
        plusMinusBtn = new javax.swing.JButton();
        resultLabel = new javax.swing.JTextField();
        numSevenBtn = new javax.swing.JButton();
        numNineBtn = new javax.swing.JButton();
        numEightBtn = new javax.swing.JButton();
        dividedByBtn = new javax.swing.JButton();
        numOneBtn = new javax.swing.JButton();
        allClearBtn = new javax.swing.JButton();
        comaBtn = new javax.swing.JButton();
        timesByBtn = new javax.swing.JButton();
        numFourBtn = new javax.swing.JButton();
        equalsBtn = new javax.swing.JButton();
        numFiveBtn = new javax.swing.JButton();
        plusBtn = new javax.swing.JButton();
        numThreeBtn = new javax.swing.JButton();
        numSixBtn = new javax.swing.JButton();
        numTwoBtn = new javax.swing.JButton();
        minusBtn = new javax.swing.JButton();
        numZeroBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(18, 18, 18));

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));

        deleteBtn.setBackground(new java.awt.Color(85, 35, 35));
        deleteBtn.setForeground(new java.awt.Color(255, 235, 235));
        deleteBtn.setText("del");
        deleteBtn.setBorderPainted(false);
        deleteBtn.setContentAreaFilled(false);
        deleteBtn.setFocusPainted(false);
        deleteBtn.setOpaque(true);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        percentBtn.setBackground(new java.awt.Color(35, 85, 70));
        percentBtn.setForeground(new java.awt.Color(230, 255, 245));
        percentBtn.setText("%");
        percentBtn.setBorderPainted(false);
        percentBtn.setContentAreaFilled(false);
        percentBtn.setFocusPainted(false);
        percentBtn.setOpaque(true);
        percentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentBtnActionPerformed(evt);
            }
        });

        plusMinusBtn.setBackground(new java.awt.Color(85, 35, 35));
        plusMinusBtn.setForeground(new java.awt.Color(255, 235, 235));
        plusMinusBtn.setText("+/-");
        plusMinusBtn.setBorderPainted(false);
        plusMinusBtn.setContentAreaFilled(false);
        plusMinusBtn.setFocusPainted(false);
        plusMinusBtn.setOpaque(true);
        plusMinusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusMinusBtnActionPerformed(evt);
            }
        });

        resultLabel.setBackground(new java.awt.Color(32, 32, 32));
        resultLabel.setForeground(new java.awt.Color(235, 235, 235));
        resultLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 10, 6, 10));
        resultLabel.setOpaque(true);

        numSevenBtn.setBackground(new java.awt.Color(45, 45, 45));
        numSevenBtn.setForeground(new java.awt.Color(230, 230, 230));
        numSevenBtn.setText("7");
        numSevenBtn.setBorderPainted(false);
        numSevenBtn.setContentAreaFilled(false);
        numSevenBtn.setFocusPainted(false);
        numSevenBtn.setOpaque(true);
        numSevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSevenBtnActionPerformed(evt);
            }
        });

        numNineBtn.setBackground(new java.awt.Color(45, 45, 45));
        numNineBtn.setForeground(new java.awt.Color(230, 230, 230));
        numNineBtn.setText("9");
        numNineBtn.setBorderPainted(false);
        numNineBtn.setContentAreaFilled(false);
        numNineBtn.setFocusPainted(false);
        numNineBtn.setOpaque(true);
        numNineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numNineBtnActionPerformed(evt);
            }
        });

        numEightBtn.setBackground(new java.awt.Color(45, 45, 45));
        numEightBtn.setForeground(new java.awt.Color(230, 230, 230));
        numEightBtn.setText("8");
        numEightBtn.setBorderPainted(false);
        numEightBtn.setContentAreaFilled(false);
        numEightBtn.setFocusPainted(false);
        numEightBtn.setOpaque(true);
        numEightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numEightBtnActionPerformed(evt);
            }
        });

        dividedByBtn.setBackground(new java.awt.Color(70, 70, 85));
        dividedByBtn.setForeground(new java.awt.Color(245, 245, 255));
        dividedByBtn.setText("÷");
        dividedByBtn.setBorderPainted(false);
        dividedByBtn.setContentAreaFilled(false);
        dividedByBtn.setFocusPainted(false);
        dividedByBtn.setOpaque(true);
        dividedByBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividedByBtnActionPerformed(evt);
            }
        });

        numOneBtn.setBackground(new java.awt.Color(45, 45, 45));
        numOneBtn.setForeground(new java.awt.Color(230, 230, 230));
        numOneBtn.setText("1");
        numOneBtn.setBorderPainted(false);
        numOneBtn.setContentAreaFilled(false);
        numOneBtn.setFocusPainted(false);
        numOneBtn.setOpaque(true);
        numOneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOneBtnActionPerformed(evt);
            }
        });

        allClearBtn.setBackground(new java.awt.Color(85, 35, 35));
        allClearBtn.setForeground(new java.awt.Color(255, 235, 235));
        allClearBtn.setText("AC");
        allClearBtn.setBorderPainted(false);
        allClearBtn.setContentAreaFilled(false);
        allClearBtn.setFocusPainted(false);
        allClearBtn.setOpaque(true);
        allClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allClearBtnActionPerformed(evt);
            }
        });

        comaBtn.setBackground(new java.awt.Color(45, 45, 45));
        comaBtn.setForeground(new java.awt.Color(230, 230, 230));
        comaBtn.setText(",");
        comaBtn.setBorderPainted(false);
        comaBtn.setContentAreaFilled(false);
        comaBtn.setFocusPainted(false);
        comaBtn.setOpaque(true);
        comaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comaBtnActionPerformed(evt);
            }
        });

        timesByBtn.setBackground(new java.awt.Color(70, 70, 85));
        timesByBtn.setForeground(new java.awt.Color(245, 245, 255));
        timesByBtn.setText("×");
        timesByBtn.setBorderPainted(false);
        timesByBtn.setContentAreaFilled(false);
        timesByBtn.setFocusPainted(false);
        timesByBtn.setOpaque(true);
        timesByBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timesByBtnActionPerformed(evt);
            }
        });

        numFourBtn.setBackground(new java.awt.Color(45, 45, 45));
        numFourBtn.setForeground(new java.awt.Color(230, 230, 230));
        numFourBtn.setText("4");
        numFourBtn.setBorderPainted(false);
        numFourBtn.setContentAreaFilled(false);
        numFourBtn.setFocusPainted(false);
        numFourBtn.setOpaque(true);
        numFourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numFourBtnActionPerformed(evt);
            }
        });

        equalsBtn.setBackground(new java.awt.Color(0, 120, 215));
        equalsBtn.setForeground(new java.awt.Color(255, 255, 255));
        equalsBtn.setText("=");
        equalsBtn.setBorderPainted(false);
        equalsBtn.setContentAreaFilled(false);
        equalsBtn.setFocusPainted(false);
        equalsBtn.setOpaque(true);
        equalsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsBtnActionPerformed(evt);
            }
        });

        numFiveBtn.setBackground(new java.awt.Color(45, 45, 45));
        numFiveBtn.setForeground(new java.awt.Color(230, 230, 230));
        numFiveBtn.setText("5");
        numFiveBtn.setBorderPainted(false);
        numFiveBtn.setContentAreaFilled(false);
        numFiveBtn.setFocusPainted(false);
        numFiveBtn.setOpaque(true);
        numFiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numFiveBtnActionPerformed(evt);
            }
        });

        plusBtn.setBackground(new java.awt.Color(70, 70, 85));
        plusBtn.setForeground(new java.awt.Color(245, 245, 255));
        plusBtn.setText("+");
        plusBtn.setBorderPainted(false);
        plusBtn.setContentAreaFilled(false);
        plusBtn.setFocusPainted(false);
        plusBtn.setOpaque(true);
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });

        numThreeBtn.setBackground(new java.awt.Color(45, 45, 45));
        numThreeBtn.setForeground(new java.awt.Color(230, 230, 230));
        numThreeBtn.setText("3");
        numThreeBtn.setBorderPainted(false);
        numThreeBtn.setContentAreaFilled(false);
        numThreeBtn.setFocusPainted(false);
        numThreeBtn.setOpaque(true);
        numThreeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numThreeBtnActionPerformed(evt);
            }
        });

        numSixBtn.setBackground(new java.awt.Color(45, 45, 45));
        numSixBtn.setForeground(new java.awt.Color(230, 230, 230));
        numSixBtn.setText("6");
        numSixBtn.setBorderPainted(false);
        numSixBtn.setContentAreaFilled(false);
        numSixBtn.setFocusPainted(false);
        numSixBtn.setOpaque(true);
        numSixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSixBtnActionPerformed(evt);
            }
        });

        numTwoBtn.setBackground(new java.awt.Color(45, 45, 45));
        numTwoBtn.setForeground(new java.awt.Color(230, 230, 230));
        numTwoBtn.setText("2");
        numTwoBtn.setBorderPainted(false);
        numTwoBtn.setContentAreaFilled(false);
        numTwoBtn.setFocusPainted(false);
        numTwoBtn.setOpaque(true);
        numTwoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTwoBtnActionPerformed(evt);
            }
        });

        minusBtn.setBackground(new java.awt.Color(70, 70, 85));
        minusBtn.setForeground(new java.awt.Color(245, 245, 255));
        minusBtn.setText("-");
        minusBtn.setBorderPainted(false);
        minusBtn.setContentAreaFilled(false);
        minusBtn.setFocusPainted(false);
        minusBtn.setOpaque(true);
        minusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusBtnActionPerformed(evt);
            }
        });

        numZeroBtn.setBackground(new java.awt.Color(45, 45, 45));
        numZeroBtn.setForeground(new java.awt.Color(230, 230, 230));
        numZeroBtn.setText("0");
        numZeroBtn.setBorderPainted(false);
        numZeroBtn.setContentAreaFilled(false);
        numZeroBtn.setFocusPainted(false);
        numZeroBtn.setOpaque(true);
        numZeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numZeroBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(percentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numZeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equalsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(allClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plusMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dividedByBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numOneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numTwoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numThreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numFourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numFiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numSixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numSevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numEightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numNineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timesByBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dividedByBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numSevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numEightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numNineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timesByBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numFourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numFiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numSixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numOneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numTwoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numThreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numZeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void percentBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_percentBtnActionPerformed
        String t = resultLabel.getText();
        if (t == null) return;
        try {
            double v = Double.parseDouble(t);
            double p = v / 100.0;
            resultLabel.setText(String.valueOf(p));
        } catch (NumberFormatException e) {
            
        }
    }// GEN-LAST:event_percentBtnActionPerformed

    private void equalsBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_equalsBtnActionPerformed
        numEnter2 = Double.parseDouble(resultLabel.getText());

        switch (op) {
            case "+":
                result = numEnter1 + numEnter2;
                break;
            case "-":
                result = numEnter1 - numEnter2;
                break;
            case "*":
                result = numEnter1 * numEnter2;
                break;
            case "/":
                result = numEnter1 / numEnter2;
                break;
            default:
                break;
        }
        resultLabel.setText(String.valueOf(result));
    }// GEN-LAST:event_equalsBtnActionPerformed

    private void allClearBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_allClearBtnActionPerformed
        resultLabel.setText("");
        numEnter1 = 0;
        numEnter2 = 0;
        result = 0;
        op = null;
    }// GEN-LAST:event_allClearBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteBtnActionPerformed
        String backspace = null;
        if (resultLabel.getText().length() > 0) {
            StringBuilder stringBuilder = new StringBuilder(resultLabel.getText());
            stringBuilder.deleteCharAt(resultLabel.getText().length() - 1);
            backspace = stringBuilder.toString();
            resultLabel.setText(backspace);
        }
    }// GEN-LAST:event_deleteBtnActionPerformed

    private void numEightBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numEightBtnActionPerformed
    enterNumbers("8");
    }// GEN-LAST:event_numEightBtnActionPerformed

    private void plusMinusBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_plusMinusBtnActionPerformed
        double nums = Double.parseDouble(String.valueOf(resultLabel.getText()));
        nums = nums * (-1);
        resultLabel.setText(String.valueOf(nums));
    }// GEN-LAST:event_plusMinusBtnActionPerformed

    private void dividedByBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dividedByBtnActionPerformed
        numEnter1 = Double.parseDouble(resultLabel.getText());
        resultLabel.setText("");
        op = "/";
    }// GEN-LAST:event_dividedByBtnActionPerformed

    private void numSevenBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numSevenBtnActionPerformed
        enterNumbers("7");
    }// GEN-LAST:event_numSevenBtnActionPerformed

    private void numNineBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numNineBtnActionPerformed
        enterNumbers("9");
    }// GEN-LAST:event_numNineBtnActionPerformed

    private void timesByBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_timesByBtnActionPerformed
        numEnter1 = Double.parseDouble(resultLabel.getText());
        resultLabel.setText("");
        op = "*";
    }// GEN-LAST:event_timesByBtnActionPerformed

    private void numFourBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numFourBtnActionPerformed
        enterNumbers("4");
    }// GEN-LAST:event_numFourBtnActionPerformed

    private void numFiveBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numFiveBtnActionPerformed
        enterNumbers("5");
    }// GEN-LAST:event_numFiveBtnActionPerformed

    private void numSixBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numSixBtnActionPerformed
        enterNumbers("6");
    }// GEN-LAST:event_numSixBtnActionPerformed

    private void minusBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_minusBtnActionPerformed
        numEnter1 = Double.parseDouble(resultLabel.getText());
        resultLabel.setText("");
        op = "-";
    }// GEN-LAST:event_minusBtnActionPerformed

    private void numOneBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numOneBtnActionPerformed
        enterNumbers("1");
    }// GEN-LAST:event_numOneBtnActionPerformed

    private void numTwoBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numTwoBtnActionPerformed
        enterNumbers("2");
    }// GEN-LAST:event_numTwoBtnActionPerformed

    private void numThreeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numThreeBtnActionPerformed
        enterNumbers("3");
    }// GEN-LAST:event_numThreeBtnActionPerformed

    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_plusBtnActionPerformed
        numEnter1 = Double.parseDouble(resultLabel.getText());
        resultLabel.setText("");
        op = "+";
    }// GEN-LAST:event_plusBtnActionPerformed

    private void numZeroBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_numZeroBtnActionPerformed
        enterNumbers("0");
    }// GEN-LAST:event_numZeroBtnActionPerformed

    private void comaBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comaBtnActionPerformed
        if (!resultLabel.getText().contains(".")) {
            resultLabel.setText(resultLabel.getText() + comaBtn.getText());
        }
    }// GEN-LAST:event_comaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KalkulatorFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allClearBtn;
    private javax.swing.JButton comaBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton dividedByBtn;
    private javax.swing.JButton equalsBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minusBtn;
    private javax.swing.JButton numEightBtn;
    private javax.swing.JButton numFiveBtn;
    private javax.swing.JButton numFourBtn;
    private javax.swing.JButton numNineBtn;
    private javax.swing.JButton numOneBtn;
    private javax.swing.JButton numSevenBtn;
    private javax.swing.JButton numSixBtn;
    private javax.swing.JButton numThreeBtn;
    private javax.swing.JButton numTwoBtn;
    private javax.swing.JButton numZeroBtn;
    private javax.swing.JButton percentBtn;
    private javax.swing.JButton plusBtn;
    private javax.swing.JButton plusMinusBtn;
    private javax.swing.JTextField resultLabel;
    private javax.swing.JButton timesByBtn;
    // End of variables declaration//GEN-END:variables
}
