/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.prakpbo.main;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane; 
import javax.swing.SwingUtilities;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author asus
 */
public class LihatDataPanel extends javax.swing.JPanel {

    private DefaultTableModel tableModel; 

    public LihatDataPanel() {
        initComponents();
        loadData();

        mahasiswaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = mahasiswaTable.getSelectedRow();
                if (row == -1) {
                    return; 
                }

                Object[] options = {"Update", "Delete", "Close"};
                int pilihan = JOptionPane.showOptionDialog(
                    null, // Parent
                    "Pilihan anda untuk data: " + tableModel.getValueAt(row, 0), // Ambil nama dari tabel
                    "Update/Delete",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    options,
                    options[0]
                );

                if (pilihan == 0) {
                    
                    MainJFrame frame = (MainJFrame) SwingUtilities.getWindowAncestor(LihatDataPanel.this);
                    frame.changeMainPanel(new TambahDataPanel(Mahasiswa.mahasiswas.get(row)));

                } else if (pilihan == 1) {
                    int konfirmasi = JOptionPane.showConfirmDialog(
                        null,
                        "Yakin ingin menghapus data ?", 
                        "Konfirmasi", 
                        JOptionPane.YES_NO_OPTION
                    );

                    if (konfirmasi == JOptionPane.YES_OPTION) {
                        Mahasiswa.mahasiswas.remove(row);
                        
                        tableModel.removeRow(row); 
                        
                        JOptionPane.showMessageDialog(null, "Data telah dihapus!");
                    }
                }
                // else (pilihan == 2 atau 'Close'), tidak melakukan apa-apa
            }
        });
    }

    private void loadData() {
        String[] column = {"Nama", "NIM", "Prodi", "Jenis Kelamin", "Status"};
        
        tableModel = new DefaultTableModel(null, column) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (Mahasiswa mhs : Mahasiswa.mahasiswas) {
            
            tableModel.addRow(new String[]{
                mhs.getNama(), mhs.getNim(),
                mhs.getProdi(), mhs.getJenisKelamin(),
                mhs.isActive() ? "Aktif" : "Tidak Aktif"
            });
        }
        
        mahasiswaTable.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mahasiswaTable = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Lihat Data Mahasiwa");

        mahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mahasiswaTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(248, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mahasiswaTable;
    // End of variables declaration//GEN-END:variables
}
