/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.prakpbo.main;

import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
import javax.swing.SwingUtilities; 
/**
 *
 * @author asus
 */
public class TambahDataPanel extends javax.swing.JPanel {

    private ButtonGroup genderButtonGroup;
    private boolean isUpdateMode = false;
    private Mahasiswa mahasiswaUpdate = null;

    
    public TambahDataPanel() {
        initComponents();
        genderButtonGroup = new ButtonGroup();
        genderButtonGroup.add(lakiLakiRadioButton);
        genderButtonGroup.add(perempuanRadioButton);
    }
    
    public TambahDataPanel(Mahasiswa mahasiswa) {
        initComponents();
        genderButtonGroup = new ButtonGroup();
        genderButtonGroup.add(lakiLakiRadioButton);
        genderButtonGroup.add(perempuanRadioButton);

        this.isUpdateMode = true;
        this.mahasiswaUpdate = mahasiswa; 

        namaTextField.setText(mahasiswa.getNama());
        nimTextField.setText(mahasiswa.getNim());
        prodiComboBox.setSelectedItem(mahasiswa.getProdi());
        
        if (mahasiswa.getJenisKelamin().equalsIgnoreCase("Laki-Laki")) {
            lakiLakiRadioButton.setSelected(true);
        } else {
            perempuanRadioButton.setSelected(true);
        }
        
        aktifCheckBox.setSelected(mahasiswa.isActive());

        kirimButton.setText("Update");
        jLabel1.setText("Update Data Mahasiswa");
    }

    private void clearForm() {
        namaTextField.setText("");
        nimTextField.setText("");
        lakiLakiRadioButton.setSelected(false);
        perempuanRadioButton.setSelected(false);
        aktifCheckBox.setSelected(false);
        genderButtonGroup.clearSelection();
        prodiComboBox.setSelectedIndex(4); // Reset prodi ke pilihan kosong
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        prodiComboBox = new javax.swing.JComboBox<>();
        lakiLakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        aktifCheckBox = new javax.swing.JCheckBox();
        kirimButton = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tambah Data Mahasiswa");

        jLabel2.setText("Nama");

        jLabel3.setText("NIM");

        jLabel4.setText("Prodi");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Status");

        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });

        prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Arsitektur", "S1 Teknik Kimia", "S1 Teknik Sipil", "" }));
        prodiComboBox.setSelectedIndex(4);
        prodiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiComboBoxActionPerformed(evt);
            }
        });

        lakiLakiRadioButton.setText("Laki Laki");
        lakiLakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiLakiRadioButtonActionPerformed(evt);
            }
        });

        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });

        aktifCheckBox.setText("Aktif");
        aktifCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktifCheckBoxActionPerformed(evt);
            }
        });

        kirimButton.setBackground(new java.awt.Color(153, 204, 255));
        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaTextField)
                            .addComponent(nimTextField)
                            .addComponent(prodiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aktifCheckBox)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lakiLakiRadioButton)
                                        .addGap(50, 50, 50)
                                        .addComponent(perempuanRadioButton))
                                    .addComponent(kirimButton))
                                .addGap(0, 124, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lakiLakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(aktifCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kirimButton)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    
    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldActionPerformed

    private void prodiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiComboBoxActionPerformed

    private void lakiLakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiLakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiLakiRadioButtonActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed

    private void aktifCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktifCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aktifCheckBoxActionPerformed

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
        // TODO add your handling code here:
        String nama = namaTextField.getText();
        String nim = nimTextField.getText();
        String prodi = (String) prodiComboBox.getSelectedItem();
        String jenisKelamin = "";
        if (lakiLakiRadioButton.isSelected()) {
            jenisKelamin = "Laki-Laki";
        } else if (perempuanRadioButton.isSelected()) {
            jenisKelamin = "Perempuan";
        }
    
        boolean isActive = aktifCheckBox.isSelected();
    
        
        if (nama.equals ("") || nim.equals("")){
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n"
                    + "- Nama atau NIM tidak terisi");
        }
        else if(jenisKelamin.equals("")){
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n"
                    + "- Opsi jenis kelamin belum dipilih");
        }
        else if(prodi.equals("")){
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n"
                    + "- Opsi prodi belum dipilih");
        }
        else if (!nama.matches("^[a-zA-Z ]+$")){
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n"
                    +"- Terdapat nomor atau karakter spesial pada Nama");
        }
        else if (nim.matches(".[a-zA-Z].") || nim.matches(".[^a-zA-Z0-9].")){
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n"
                    +"- Terdapat alfabet atau karakter spesial pada NIM");
        }
        else if (!(nim.length() == 10)){
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n"
                    +"- Jumlah digit pada NIM kurang dari 10");
        }
        else {
            
            if (isUpdateMode) {
                
                
                boolean sudahAda = false;
                String namaDuplikat = "";
                
                
                if (!nim.equals(mahasiswaUpdate.getNim())) {
                    for (Mahasiswa mhs : Mahasiswa.mahasiswas) {
                        if (mhs.getNim().equals(nim)) {
                            sudahAda = true;
                            namaDuplikat = mhs.getNama();
                            break;
                        }
                    }
                }

                if (sudahAda) {
                    JOptionPane.showMessageDialog(this,"Data gagal diupdate:\n" +
                            "- NIM sudah terdaftar atas nama: " + namaDuplikat);
                } else {
                    
                    mahasiswaUpdate.setNama(nama);
                    mahasiswaUpdate.setNim(nim);
                    mahasiswaUpdate.setProdi(prodi);
                    mahasiswaUpdate.setJenisKelamin(jenisKelamin);
                    mahasiswaUpdate.setActive(isActive);
                    
                    JOptionPane.showMessageDialog(this, "Sukses mengupdate data " + nama);
                    
                   
                    MainJFrame frame = (MainJFrame) SwingUtilities.getWindowAncestor(this);
                    frame.changeMainPanel(new LihatDataPanel());
                }

            } else {
                boolean sudahAda = false;
                String namaDuplikat = "";

                for (Mahasiswa mhs : Mahasiswa.mahasiswas) {
                    if (mhs.getNim().equals(nim)) {
                        sudahAda = true;
                        namaDuplikat = mhs.getNama();
                        break;
                    }
                }

                if (sudahAda) {
                    JOptionPane.showMessageDialog(this,"Data gagal ditambahkan:\n" +
                            "- NIM sudah terdaftar atas nama: " + namaDuplikat);
                }else{
                    Mahasiswa mahasiswa = new Mahasiswa(nama, nim, prodi, jenisKelamin, isActive);
                    Mahasiswa.mahasiswas.add(mahasiswa);

                    JOptionPane.showMessageDialog(this, "Sukses menambahkan data mahasiswa " + nama);
                    clearForm();    
                }
            }
        }      
    }//GEN-LAST:event_kirimButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kirimButton;
    private javax.swing.JRadioButton lakiLakiRadioButton;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JComboBox<String> prodiComboBox;
    // End of variables declaration//GEN-END:variables
}
